### ISSUE TITLE
Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.

### ISSUE THREAD

**Issue by crapthings** [pmndrs/zustand#1023]
"zustand": "^4.0.0-rc.1"
"next": "^12.1.6",
"react": "^18.1.0",
"react-dom": "^18.1.0",

```
const loading = loginStore((state) => state.loading)
```

the issue remains the same after i revert to 4.0 beta3

**Comment by dai-shi** [comment]
Hmm, it should have fixed when reported in #886.
This looks different from #987.

Does anyone else have this issue?

**Comment by crapthings** [comment]
```
Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.
    at Object.useSyncExternalStore (/Users/monsterstep/dev/nextjs-playground/nextone/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5074:11)
    at useSyncExternalStore (/Users/monsterstep/dev/nextjs-playground/nextone/node_modules/react/cjs/react.development.js:1674:21)
    at useSyncExternalStoreWithSelector (/Users/monsterstep/dev/nextjs-playground/nextone/node_modules/use-sync-external-store/cjs/use-sync-external-store-shim/with-selector.development.js:145:15)
    at useStore (file:///Users/monsterstep/dev/nextjs-playground/nextone/node_modules/zustand/esm/index.mjs:8:17)
    at useBoundStore (file:///Users/monsterstep/dev/nextjs-playground/nextone/node_modules/zustand/esm/index.mjs:14:51)
    at LoginPage (webpack-internal:///./components/admin-login.js:18:77)
    at renderWithHooks (/Users/monsterstep/dev/nextjs-playground/nextone/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5471:16)
    at renderIndeterminateComponent (/Users/monsterstep/dev/nextjs-playground/nextone/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5544:15)
    at renderElement (/Users/monsterstep/dev/nextjs-playground/nextone/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5759:7)
    at renderNodeDestructive (/Users/monsterstep/dev/nextjs-playground/nextone/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5898:11)
```

**Comment by dai-shi** [comment]
I don't see anything unexpected in the screenshots.

Here, we have getServerSnapshot with a fallback to avoid the error.
https://github.com/pmndrs/zustand/blob/v4.0.0-rc.1/src/react.ts#L37

**Comment by dai-shi** [comment]
If you have further questions, please open a [new discussion](https://github.com/pmndrs/zustand/discussions/new).
